version: "3"

services:
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - www
    app:
        image: www
        expose:
            - "5000"