version: "3"

services:
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs
        ports:
            - "443:443"
        depends_on:
            - template
            - www
    template:
        image: template
        expose:
            - "5000"
    www:
        image: www
        expose:
            - "5000"
